site_name: sverige Linux
site_url: https://ollipix.github.io/sverige-docs/
site_description: Independent, source-built x86_64 operating system documentation.

theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
  palette:
    scheme: slate
    primary: black
    accent: lime
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

nav:
  - Home: index.md
  - About: about.md
  - Installation Guide: guide.md
  
