site_name: sverige Linux
site_url: https://ollipix.github.io/sverige-docs/
site_description: Independent, source-built x86_64 operating system documentation.

theme:
  name: material
  logo: assets/images/Logo.png
  favicon: assets/images/Logo.png
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: lime
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list

nav:
  - Home: index.md
  - About: about.md
  - Installation Guide: guide.md
  
